### ISSUE TITLE
Tempus stats not updating since October 8th. 

### ISSUE THREAD

**Issue by Rubobin** [ahedgehogtf/tempus-completion#1]
Dear Hedgehog, 

My tempus stats on https://tempus.ahedgehog.org/ don't update, and haven't been updated since October 8th, while my last active time IS properly registered.

Is this something you can fix, or is there something I need to do to ensure proper updating of my scores? 

My profile: https://tempus.ahedgehog.org/player?playerid=59726

Cheers,
Rubo

**Comment by ahedgehogtf** [comment]
Hi Rubobin! There was a bug preventing the scraper from running. I fixed it in 8539f95. Your stats should be all up-to-date!
